---
driver_plugin: digitalocean
driver_config:
  flavor_id: 66
  require_chef_omnibus: latest

platforms:
- name: debian-7-0-x64
- name: ubuntu-13-10-x64

suites:
- name: default
  run_list:
  - recipe[sidekiq-test]
- name: sidekiq-delete
  run_list:
  - recipe[sidekiq-test::delete]
